version: "3.8"
services:
  resilio-sync:
    container_name: resilio-sync
    image: resilio/sync
    user: 1000:1000
    ports:
      - 8888:8888
      - 55555
    volumes:
      - ${SYNC_FOLDER}:/mnt/sync
    restart: unless-stopped
    environment: 
      - UID=1000
      - GID=1000
      - TZ=America/Montreal
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true
