---
kind: pipeline
name: notification Build starting
steps:
- failure: ignore
  image: plugins/slack
  name: notification
  settings:
    channel: drone-ci
    template: |
      Build starting
      {{ uppercasefirst build.event }} on branch {{ build.branch }} from repo {{repo.name}}
      <{{ build.link }}|Visit build #{{build.number}} page ➡️>
    webhook:
      from_secret: SLACK_WEBHOOK_URL
type: docker
---
kind: pipeline
name: terraform
steps:
- commands:
  - apt-get update && apt-get install -y curl ca-certificates gnupg lsb-release software-properties-common
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
  - apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com
    $(lsb_release -cs) main"
  - apt-get update && apt-get install -y terraform
  - cd ./terraform
  - terraform -v
  - terraform init
  - terraform validate
  - terraform plan
  - terraform apply -auto-approve
  environment:
    CLOUDFLARE_API_TOKEN:
      from_secret: CLOUDFLARE_API_TOKEN
    CLOUDFLARE_EMAIL:
      from_secret: CLOUDFLARE_EMAIL
  image: ubuntu
  name: terraform
type: docker
---
kind: pipeline
name: notification Build finished
steps:
- failure: ignore
  image: plugins/slack
  name: notification
  settings:
    channel: drone-ci
    template: |
      Build finished
      {{ uppercasefirst build.event }} on branch {{ build.branch }} from repo {{repo.name}}
      <{{ build.link }}|Visit build #{{build.number}} page ➡️>
    webhook:
      from_secret: SLACK_WEBHOOK_URL
type: docker
