---
kind: pipeline
name: deploy cron
steps:
- commands:
  - apk update && apk --no-cache add bash curl docker-compose && curl --version &&
    bash --version && docker-compose version
  - /bin/bash /drone/src/scripts/deploy.sh
  environment:
    CF_API_EMAIL:
      from_secret: CF_API_EMAIL
    CF_API_KEY:
      from_secret: CF_API_KEY
    CLIENT_ID:
      from_secret: CLIENT_ID
    CLIENT_SECRET:
      from_secret: CLIENT_SECRET
    DRONE_CI: true
    DRONE_GITHUB_CLIENT_ID:
      from_secret: DRONE_GITHUB_CLIENT_ID
    DRONE_GITHUB_CLIENT_SECRET:
      from_secret: DRONE_GITHUB_CLIENT_SECRET
    DRONE_RPC_SECRET:
      from_secret: DRONE_RPC_SECRET
    DRONE_USER_CREATE:
      from_secret: DRONE_USER_CREATE
    DRONE_USER_FILTER:
      from_secret: DRONE_USER_FILTER
    OPENVPN_PASSWORD:
      from_secret: OPENVPN_PASSWORD
    OPENVPN_USERNAME:
      from_secret: OPENVPN_USERNAME
    SECRET:
      from_secret: SECRET
    UPDATE_HC_UUID:
      from_secret: UPDATE_HC_UUID
  image: docker:20.10.12
  name: deploy prod
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  cron:
  - daily
  event:
  - cron
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: pipeline
name: deploy push
steps:
- commands:
  - apk update && apk --no-cache add bash curl docker-compose && curl --version &&
    bash --version && docker-compose version
  - /bin/bash /drone/src/scripts/deploy.sh
  environment:
    CF_API_EMAIL:
      from_secret: CF_API_EMAIL
    CF_API_KEY:
      from_secret: CF_API_KEY
    CLIENT_ID:
      from_secret: CLIENT_ID
    CLIENT_SECRET:
      from_secret: CLIENT_SECRET
    DRONE_CI: true
    DRONE_GITHUB_CLIENT_ID:
      from_secret: DRONE_GITHUB_CLIENT_ID
    DRONE_GITHUB_CLIENT_SECRET:
      from_secret: DRONE_GITHUB_CLIENT_SECRET
    DRONE_RPC_SECRET:
      from_secret: DRONE_RPC_SECRET
    DRONE_USER_CREATE:
      from_secret: DRONE_USER_CREATE
    DRONE_USER_FILTER:
      from_secret: DRONE_USER_FILTER
    OPENVPN_PASSWORD:
      from_secret: OPENVPN_PASSWORD
    OPENVPN_USERNAME:
      from_secret: OPENVPN_USERNAME
    SECRET:
      from_secret: SECRET
    UPDATE_HC_UUID:
      from_secret: UPDATE_HC_UUID
  image: docker:20.10.12
  name: deploy prod
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  event:
  - push
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
