version: "3.8"
services:
  drone:
    image: drone/drone:1
    container_name: drone
    environment:
      - DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET
      - DRONE_RPC_SECRET
      - DRONE_SERVER_HOST
      - DRONE_SERVER_PROTO
      - DRONE_USER_FILTER
      - DRONE_USER_CREATE
      - TZ
    volumes:
      - /var/lib/drone:/data
    restart: always
    expose:
      - 80
    networks:
      - web
    labels:
      - "traefik.enable=true"
  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO
      - DRONE_RPC_HOST
      - DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: always
    
networks:
  web:
    external: true
