version: "3.7"
services:
  drone:
    image: drone/drone:1
    container_name: drone
    environment:
      - DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET
      - DRONE_RPC_SECRET
      - DRONE_SERVER_HOST
      - DRONE_SERVER_PROTO
      - DRONE_USER_FILTER
      - DRONE_USER_CREATE
      - TZ
    volumes:
      - /var/lib/drone:/data
    restart: always
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.drone.entrypoints=web,websecure"
      - "traefik.http.routers.drone.middlewares=redirect_scheme,secured_headers"
      - "traefik.http.routers.drone.rule=Host(`drone.${DOMAIN}`)"
      - "traefik.http.routers.drone.service=drone@docker"
      - "traefik.http.routers.drone.tls.certresolver=leresolver"
      - "traefik.http.routers.drone.tls=true"
      - "traefik.http.services.drone.loadbalancer.server.port=80"
  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO
      - DRONE_RPC_HOST
      - DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: always
networks:
  web:
    external: true
