version: "3.8"
services:
  drone:
    image: drone/drone:2
    container_name: drone
    environment:
      - DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET
      - DRONE_RPC_SECRET
      - DRONE_SERVER_HOST
      - DRONE_SERVER_PROTO
      - DRONE_USER_FILTER
      - DRONE_USER_CREATE
      - DRONE_STARLARK_ENABLE=true
      - DRONE_JSONNET_ENABLED=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_TRACE=true
    volumes:
      - /mnt/glusterfs/drone:/data
    restart: always
    expose:
      - 80
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.persistence == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.drone.loadbalancer.server.port=80"

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO
      - DRONE_RPC_HOST
      - DRONE_RPC_SECRET
      - DRONE_TRACE=true
      - DRONE_DEBUG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - "3000"
    restart: always
    deploy:
      mode: global
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  drone-runner-manager:
    container_name: drone-runner-manager
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO
      - DRONE_RPC_HOST
      - DRONE_RPC_SECRET
      - DRONE_TRACE=true
      - DRONE_DEBUG=true
      - DRONE_RUNNER_LABELS=swarm-role:manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - "3000"
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.master == true

networks:
  traefik-public:
    external: true
    driver: overlay
