version: "3.8"

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://couchdb:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - 8080
    networks:
      - swarmpit-network
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
      placement:
        constraints:
          - node.labels.persistence == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.swarmpit.entrypoints=websecure"
        - "traefik.http.routers.swarmpit.middlewares=oauth@file, secured_headers@file"
        - "traefik.http.routers.swarmpit.service=swarmpit@docker"
        - "traefik.http.routers.swarmpit.tls=true"
        - "traefik.http.routers.swarmpit.tls.certresolver=leresolver"
        - "traefik.http.routers.swarmpit.rule=Host(`swarmpit.gordon-pn.com`)"

  couchdb:
    image: treehouses/couchdb:2.3.1
    volumes:
      - /mnt/glusterfs/swarmpit/couchdb:/opt/couchdb/data
    networks:
      - swarmpit-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      placement:
        constraints:
          - node.labels.persistence == true

  influxdb:
    image: influxdb:1.7
    volumes:
      - /mnt/glusterfs/swarmpit/influxdb:/var/lib/influxdb
    networks:
      - swarmpit-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      placement:
        constraints:
          - node.labels.persistence == true

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit-network
    deploy:
      mode: global
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
      labels:
        swarmpit.agent: "true"

networks:
  swarmpit-network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
    driver: overlay
    attachable: true
