version: "3.8"

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://couchdb:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - 8080
    networks:
      - swarmpit-network
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
      placement:
        constraints:
          - node.labels.main-node == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik-public"

  couchdb:
    image: couchdb:2.3.0
    volumes:
      - swarmpit-couchdb:/opt/couchdb/data
    networks:
      - swarmpit-network
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
        reservations:
          cpus: "0.15"
          memory: 128M
      placement:
        constraints:
          - node.labels.main-node == true

  influxdb:
    image: influxdb:1.7
    volumes:
      - swarmpit-influxdb:/var/lib/influxdb
    networks:
      - swarmpit-network
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: 512M
        reservations:
          cpus: "0.30"
          memory: 128M
      placement:
        constraints:
          - node.labels.main-node == true

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit-network
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.10"
          memory: 64M
        reservations:
          cpus: "0.05"
          memory: 32M
      labels:
        swarmpit.agent: "true"

networks:
  swarmpit-network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
    driver: overlay
    attachable: true

volumes:
  swarmpit-couchdb:
    driver: local
  swarmpit-influxdb:
    driver: local
