version: '3.8'
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    network_mode: host
    ports:
      - 32400:32400
    volumes:
      - /media/drive/plex/config:/config
      - /media/drive/plex/data/movies:/movies
      - /media/drive/plex/data/tv:/tv
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      placement:
        constraints:
          - node.labels.persistence == true
          - node.labels.name == rpi3
