version: '3.8'
services:
  droppy:
    image: silverwind/droppy
    container_name: droppy
    volumes:
      - droppy-appdata:/config
      - ${DROPPY_FOLDER}:/files
    restart: unless-stopped
    expose:
      - 8989
    environment: 
      - UID=1000
      - GID=1000
      - TZ
    networks:
      - web
    labels:
      - "traefik.enable=true"

volumes: 
  droppy-appdata:
    external: 
      name: droppy-appdata

networks:
  web:
    external: true
