version: '3.8'
services:
  droppy:
    image: silverwind/droppy
    container_name: droppy
    volumes:
      - droppy-appdata:/config
      - ${DROPPY_FOLDER}:/files
    restart: unless-stopped
    expose:
      - 8989
    environment:
      - UID=1000
      - GID=1000
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.droppy.loadbalancer.server.port=8989"

volumes:
  droppy-appdata:
    external:
      name: droppy-appdata

networks:
  traefik-public:
    external: true
    driver: overlay
