version: "3.7"

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL
      - CF_API_KEY
      - TZ
    volumes:
      - ./letsencrypt:/letsencrypt
      #- ./traefik.log:/traefik.log
      #- ./access.log:/access.log
      - ./traefik.yaml:/traefik.yaml
      - ./dynamic_conf:/dynamic_conf
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirect_scheme.redirectscheme.permanent=true"
      - "traefik.http.middlewares.redirect_scheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.secured_headers.headers.browserxssfilter=true"
      - "traefik.http.middlewares.secured_headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.secured_headers.headers.forcestsheader=true"
      - "traefik.http.middlewares.secured_headers.headers.sslredirect=true"
      - "traefik.http.middlewares.secured_headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.secured_headers.headers.stspreload=true"
      - "traefik.http.middlewares.secured_headers.headers.stsseconds=315360000"
      - "traefik.http.routers.http_catchall.entrypoints=web"
      - "traefik.http.routers.http_catchall.middlewares=redirect_scheme,secured_headers"
      - "traefik.http.routers.http_catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest
    restart: always
    networks:
      - web
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - SECRET
      - COOKIE_DOMAIN=$DOMAIN
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAIN
      - URL_PATH=/_oauth
      - WHITELIST=$CF_API_EMAIL
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LIFETIME=2592000
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.oauth.loadbalancer.server.port=4181"

networks:
  web:
    external: true
