version: "3.8"
services:
  traefik:
    image: traefik:2.6
    restart: always
    container_name: traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    expose:
      - 8080
    environment:
      - CF_API_EMAIL
      - CF_API_KEY
    volumes:
      - /mnt/glusterfs/traefik/letsencrypt:/letsencrypt
      #- ./traefik.log:/traefik.log
      #- ./access.log:/access.log
      - ./traefik.yaml:/traefik.yaml
      - ./dynamic_conf:/dynamic_conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      placement:
        constraints:
          - node.labels.master == true
          - node.labels.persistence == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

  oauth:
    container_name: oauth
    image: npawelek/traefik-forward-auth:latest
    restart: always
    expose:
      - 4181
    networks:
      - traefik-public
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - SECRET
      - COOKIE_DOMAIN=gordon-pn.com
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.gordon-pn.com
      - URL_PATH=/_oauth
      - WHITELIST=${CF_API_EMAIL}
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LIFETIME=2592000
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=traefik-public"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      placement:
        constraints:
          - node.labels.master == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.oauth.loadbalancer.server.port=4181"

networks:
  traefik-public:
    external: true
    driver: overlay
