version: "3.8"
services:
  traefik:
    image: traefik:2.4
    restart: always
    container_name: traefik
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    expose:
      - 8080
    environment:
      - TZ=America/Montreal
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    volumes:
      - ./letsencrypt:/letsencrypt
      #- ./traefik.log:/traefik.log
      #- ./access.log:/access.log
      - ./traefik.yaml:/traefik.yaml
      - ./dynamic_conf:/dynamic_conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest
    restart: always
    expose:
      - 4181
    networks:
      - traefik-public
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - SECRET
      - COOKIE_DOMAIN=$DOMAIN
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAIN
      - URL_PATH=/_oauth
      - WHITELIST=$CF_API_EMAIL
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LIFETIME=2592000
      - TZ=America/Montreal
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=traefik-public"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.oauth.loadbalancer.server.port=4181"

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true
