version: "3.8"

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    expose: 
      - 8080
    environment:
      - CF_API_EMAIL
      - CF_API_KEY
      - TZ
    volumes:
      - ./letsencrypt:/letsencrypt
      #- ./traefik.log:/traefik.log
      #- ./access.log:/access.log
      - ./traefik.yaml:/traefik.yaml
      - ./dynamic_conf:/dynamic_conf
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    labels:
      - "traefik.enable=true"
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest
    restart: always
    expose:
      - 4181
    networks:
      - web
    security_opt:
      - no-new-privileges:true
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - SECRET
      - COOKIE_DOMAIN=$DOMAIN
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$DOMAIN
      - URL_PATH=/_oauth
      - WHITELIST=$CF_API_EMAIL
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LIFETIME=2592000
    labels:
      - "traefik.enable=true"

networks:
  web:
    external: true
