http:

  routers:

    http_catch_all:
      entryPoints:
        - web
      middlewares:
        - redirect_scheme
        - secured_headers
      service: "noop@internal"
      rule: "HostRegexp(`{host:.+}`)"

    api:
      entryPoints:
        - websecure
      middlewares:
        - oauth
        - rate_limit
        - secured_headers
      service: "api@internal"
      tls:
        certResolver: "leresolver"
      rule: "Host(`monitor.gordon-pn.com`)"

    oauth:
      entryPoints:
        - websecure
      middlewares:
        - oauth
        - rate_limit
        - secured_headers
      service: "oauth@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`oauth.gordon-pn.com`)"

    filebrowser:
      entryPoints:
        - websecure
      middlewares:
        - oauth
        - secured_headers
      service: "filebrowser@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`filebrowser.gordon-pn.com`)"

    drone:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "drone@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`drone.gordon-pn.com`)"

    personal-site:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "personal-site@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`gordon-pn.com`) || Host(`www.gordon-pn.com`)"

    speedtest-site:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "speedtest@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`speed.gordon-pn.com`)"

    github-stats:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "github-stats@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`stats.gordon-pn.com`)"

    shopify:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "shopify@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`shopify.gordon-pn.com`)"

    meta-search:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "meta-search@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`search.gordon-pn.com`)"

    hotdeals-site:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "deals@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`deals.gordon-pn.com`)"

    conventions-site:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
      service: "conventions-guide@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`conventions.gordon-pn.com`)"

  middlewares:

    rate_limit:
      rateLimit:
        average: 100
        burst: 50

    oauth:
      forwardAuth:
        address: "http://oauth:4181"
        trustForwardHeader: true
        authResponseHeaders: ["X-Forwarded-User"]

    secured_headers:
      headers:
        accessControlMaxAge: 100
        browserXssFilter: true
        # contentSecurityPolicy: "default-src https: 'unsafe-inline' 'unsafe-eval'"
        contentTypeNosniff: true
        featurePolicy: "accelerometer 'none'; camera 'none'; microphone 'none'; geolocation 'none'; midi 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none';"
        forceSTSHeader: true
        frameDeny: true
        hostsProxyHeaders: ["X-Forwarded-Host"]
        referrerPolicy: "no-referrer-when-downgrade"
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 315360000

    redirect_scheme:
      redirectScheme:
        permanent: true
        scheme: "https"
