http:

  routers:

    http_catch_all:
      entryPoints:
        - web
      middlewares:
        - redirect_scheme
        - secured_headers
      service: "noop@internal"
      rule: "HostRegexp(`{host:.+}`)"

    api:
      entryPoints:
        - websecure
      middlewares:
        - redirect_scheme
        - secured_headers
        - oauth
        - rate_limit
      service: "api@internal"
      tls:
        certResolver: "leresolver"
      rule: "Host(`monitor.gordon-pn.com`)"

    oauth:
      entryPoints:
        - websecure
      middlewares:
        - rate_limit
        - secured_headers
        - oauth
      service: "oauth-traefik@docker" 
      tls:
        certResolver: "leresolver"
      rule: "Host(`oauth.gordon-pn.com`)"

    dozzle:
      entryPoints:
        - websecure
      middlewares:
        - oauth
        - rate_limit
        - redirect_scheme
        - secured_headers
      service: "dozzle-dozzle@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`dozzle.gordon-pn.com`)"

    droppy:
      entryPoints:
        - websecure
      middlewares:
        - secured_headers
        - redirect_scheme
      service: "droppy-droppy@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`droppy.gordon-pn.com`)"
      
    drone:
      entryPoints: 
        - websecure
      middlewares:
        - redirect_scheme
        - secured_headers
      service: "drone-drone@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`drone.gordon-pn.com`)"

    personal-site:
      entryPoints:
        - websecure
      middlewares:
        - rate_limit
        - redirect_scheme
        - secured_headers
      service: "personal-site-personal-site@docker"
      tls:
        certResolver: "leresolver"
      rule: "Host(`gordon-pn.com`)"

  middlewares:

    rate_limit:
      rateLimit:
        average: 100
        burst: 50

    oauth:
      forwardAuth:
        address: "http://oauth:4181"
        trustForwardHeader: true
        authResponseHeaders: ["X-Forwarded-User"]

    secured_headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 315360000
        referrerPolicy: "same-origin" 
        hostsProxyHeaders: ["X-Forwarded-Host"]
        accessControlMaxAge: 100

    redirect_scheme:
      redirectScheme:
        permanent: true
        scheme: "https"
