version: "3.7"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - dev-mongodb-library:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment: 
      - TZ
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_MONGODB_AUTH_DATABASE
      - ME_CONFIG_MONGODB_AUTH_PASSWORD
      - ME_CONFIG_MONGODB_AUTH_USERNAME
      - ME_CONFIG_MONGODB_ENABLE_ADMIN
      - ME_CONFIG_MONGODB_PORT
      - ME_CONFIG_MONGODB_SERVER
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME

volumes:
  dev-mongodb-library:
    external:
      name: dev-mongodb-library
