version: "3.8"
services:
  adguard:
    image: adguard/adguardhome
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      - traefik-public
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 80
        published: 4000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

volumes:
  adguard_work:
  adguard_conf:

networks:
  traefik-public:
    external: true
    driver: overlay
