version: "3.8"
services:
  adguard:
    image: adguard/adguardhome
    volumes:
      - /mnt/glusterfs/adguardhome/work:/opt/adguardhome/work
      - /mnt/glusterfs/adguardhome/conf:/opt/adguardhome/conf
    networks:
      - traefik-public
    ports:
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 80
        published: 4000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      placement:
        constraints:
          - node.labels.master == true
          - node.labels.persistence == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"

networks:
  traefik-public:
    external: true
    driver: overlay
