version: "3.3"
services:
  drone-runner-docker:
    container_name: runner
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_PROTO
      - DRONE_RPC_HOST
      - DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
      - TZ=America/Montreal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: always
