version: "3.8"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    ports:
      - 8080:8080
      # - 50000:50000 # for agents
    volumes:
      - /mnt/share/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.jenkins.entrypoints=websecure"
        - "traefik.http.routers.jenkins.middlewares=secured_headers@file"
        - "traefik.http.routers.jenkins.service=jenkins@docker"
        - "traefik.http.routers.jenkins.tls=true"
        - "traefik.http.routers.jenkins.tls.certresolver=leresolver"
        - "traefik.http.routers.jenkins.rule=Host(`jenkins.gordon-pn.com`)"
      placement:
        constraints:
          - node.labels.persistence == true
          - node.labels.master == true

networks:
  traefik-public:
    external: true
    driver: overlay
