version: '3.7'

services:
  slack-docker:
    container_name: slack-docker
    image: int128/slack-docker
    restart: unless-stopped
    environment: 
      - webhook=$SLACK_WEBHOOK_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock