version: "3.8"
services:
  slack-docker:
    container_name: slack-docker
    image: int128/slack-docker
    restart: unless-stopped
    environment:
      - webhook=$SLACK_WEBHOOK_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      placement:
        constraints:
          - node.labels.master == true
