version: "3.8"
services:
  slack-docker:
    container_name: slack-docker
    image: int128/slack-docker
    restart: unless-stopped
    environment:
      - webhook=$SLACK_WEBHOOK_URL
      - TZ=America/Toronto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true
