version: "3.8"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.master == true
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true
