version: '3.8'
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/share/openvpn:/etc/openvpn/custom
      - /mnt/share/transmission:/data/completed
    environment:
      - LOCAL_NETWORK=192.168.50.0/24
      - OPENVPN_CONFIG=ca-tr
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - OPENVPN_PASSWORD
      - OPENVPN_PROVIDER=custom
      - OPENVPN_USERNAME
      - PGID=1001
      - PUID=1001
      - TRANSMISSION_WEB_UI=combustion
    ports:
      - 9091:9091
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
      restart_policy:
        window: 120s
      placement:
        constraints:
          - node.labels.persistence == true
          - node.labels.name == rpi3
