version: "3.8"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /mnt/glusterfs/syncthing:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.persistence == true
